---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: coffeehouse
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://github.com/rshep3087/coffeehouse