services:
  coffeehouse:
    image: coffeehouse
    env_file:
      - docker.env
    depends_on:
      - db
      - nats
    build:
      context: .
      dockerfile: ./Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - 8080:8080

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coffeehousedb
    ports:
      - 5432:5432
    volumes:
      - coffeehouse:/var/lib/postgresql/data
  
  nats:
    image: nats
    ports:
      - 4222:4222

  redis:
    image: redis
    ports:
      - 6379:6379

  jaeger:
    image: jaegertracing/all-in-one:1.60
    ports:
      - 16686:16686
  
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.111.0
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - 4317:4317

volumes:
  coffeehouse:
    name: coffeehouse