POST http://localhost:8080/v1/recipes HTTP/1.1
content-type: application/json

{
    "recipe_name": "sample",
    "brew_method": "chemex",
    "coffee_weight": 20.0,
    "weight_unit": "g",
    "grind_size": 21,
    "water_weight": 500.0,
    "water_unit": "g"
}

### Get single recipe

GET http://localhost:8080/v1/recipes/1 HTTP/1.1