apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: coffeehouse
  name: coffeehouse
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: coffeehouse
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: coffeehouse
    spec:
      containers:
        - env:
            - name: COFFEEHOUSE_DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: COFFEEHOUSE_DB_HOST
                  name: docker-env
            - name: COFFEEHOUSE_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: COFFEEHOUSE_DB_PASSWORD
                  name: docker-env
            - name: COFFEEHOUSE_DB_TLS
              valueFrom:
                configMapKeyRef:
                  key: COFFEEHOUSE_DB_TLS
                  name: docker-env
            - name: COFFEEHOUSE_LISTEN_ADDR
              valueFrom:
                configMapKeyRef:
                  key: COFFEEHOUSE_LISTEN_ADDR
                  name: docker-env
            - name: COFFEEHOUSE_NATS_URL
              valueFrom:
                configMapKeyRef:
                  key: COFFEEHOUSE_NATS_URL
                  name: docker-env
          image: ghcr.io/rshep3087/coffeehouse:latest
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8080/health
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 10
          name: coffeehouse
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
      restartPolicy: Always
