---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: cnpg-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.21.x"
      sourceRef:
        kind: HelmRepository
        name: cnpg-system
        namespace: flux-system
  values:
    # CloudNative-PG operator configuration
    monitoring:
      enabled: true
    webhook:
      port: 9443
---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: coffeehouse-postgres
  namespace: default
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised

  postgresql:
    parameters:
      max_connections: "200"
      shared_preload_libraries: ""
      dynamic_shared_memory_type: "posix"

  bootstrap:
    initdb:
      database: coffeehousedb
      owner: user
      secret:
        name: coffeehouse-postgres-credentials

  storage:
    size: 1Gi
    storageClass: standard

  monitoring:
    enabled: true

  # Enable automatic failover
  failoverDelay: 0