---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dragonfly
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: dragonfly
      version: "v1.22.x"
      sourceRef:
        kind: OCIRepository
        name: dragonfly
        namespace: flux-system
  values:
    replicaCount: 1

    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"

    # Dragonfly configuration
    extraArgs:
      - --maxmemory=256mb
      - --default_lua_flags=allow-undeclared-keys

    # Service configuration
    service:
      type: ClusterIP
      port: 6379