---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nats
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: nats
      version: "1.1.x"
      sourceRef:
        kind: HelmRepository
        name: nats
        namespace: flux-system
  values:
    config:
      jetstream:
        enabled: true
        fileStore:
          pvc:
            size: 1Gi
            storageClassName: standard

    container:
      image:
        repository: nats
        tag: "2.10-alpine"

    reloader:
      enabled: true

    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"

    # Enable monitoring
    natsBox:
      enabled: true

    # Service configuration
    service:
      enabled: true
      ports:
        client:
          port: 4222
        monitoring:
          port: 8222