CREATE TYPE brew_method AS ENUM ('chemex', 'v60', 'french press', 'aeropress');
CREATE TYPE temp_unit AS ENUM ('F', 'C');
CREATE TYPE weight_unit AS ENUM ('g', 'oz');


CREATE TABLE public.recipes (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	recipe_name varchar NOT NULL,
	brew_method brew_method NOT NULL,
	coffee_weight float8 NOT NULL,
	weight_unit weight_unit NOT NULL,
	grind_size int NOT NULL,
	water_weight float8 NOT NULL,
	water_unit varchar NOT NULL,
	water_temp float8 NULL,
	water_temp_unit varchar NULL,
	CONSTRAINT recipes_pk PRIMARY KEY (id)
);
COMMENT ON TABLE public.recipes IS 'holds coffee recipes users add';
